'use client'

import { useMemo, useState, type ReactNode } from 'react'
import { ArrowUpRight, ChevronDown, Circle, Mail, Menu, MessageCircle, Sparkles, TrainFront, UserRound, BriefcaseBusiness, X } from 'lucide-react'

const experiences = [
  { title: 'Estúdio Cerise', role: 'Fundadora', text: 'Produção de marcas, branding, criação de posts, camisetas e design em geral.', color: 'yellow', current: true },
  { title: 'Desenvolvedora Frontend', role: 'Atual', text: 'Criação de aplicações frontend com atenção à experiência, clareza e detalhe.', color: 'pink', current: true },
  { title: 'Vale · Estrada de Ferro Carajás', role: 'Estágio em Desenvolvimento', text: 'Aplicações de telemetria e manutenção de locomotivas, aprendendo a operação ferroviária e sua importância para o Maranhão.', color: 'blue', train: true, photos: [
    { src: '/images/vale-trilha.jpg', caption: 'dia de Vale ♡' },
    { src: '/images/vale-sala-controle.jpg', caption: 'time da sala de controle' },
    { src: '/images/vale-uniforme.jpg', caption: 'uniforme oficial' },
  ] },
  { title: 'Proflab Distribuidora', role: 'Social media · tráfego pago · design', text: 'Planejamento e criação de conteúdo para presença digital, incluindo a cobertura do 3º COMAC.', color: 'lime', photos: [
    { src: '/images/proflab-comac-equipe.jpg', caption: 'equipe no 3º COMAC' },
  ] },
  { title: 'Blitz Redação', role: 'Social media', text: 'Conteúdo, direção criativa e rotina de redes sociais.', color: 'yellow' },
  { title: 'Kiola Mármores', role: 'Design e comunicação visual', text: 'Peças visuais para comunicar beleza e acabamento.', color: 'pink' },
  { title: 'UNDB · Análise de Sistemas', role: 'Formação', text: 'Background em inovação, tecnologia e audiovisual.', color: 'blue' },
]

type Project = { title: string; category: string; tone: string; file: string; src: string; video?: string; text: string }

const projects: Project[] = [
  { title: 'Flor de Mulher', category: 'Marcas e Branding', tone: 'pink', file: 'flor_de_mulher.ai', src: '/images/flor-de-mulher-etiquetas.jpg', text: 'Identidade visual e etiquetas para a loja Flor de Mulher: magenta, dourado e um toque floral em cada detalhe.' },
  { title: 'Um dia no 3º COMAC', category: 'Vídeos', tone: 'lime', file: 'comac_reels.mp4', src: '/images/proflab-comac-poster.jpg', video: '/images/proflab-comac.mp4', text: 'Gravação e edição do reels “Um dia com a Prof-Lab no 3º COMAC”, Congresso Maranhense de Análises Clínicas e Medicina Laboratorial.' },
  { title: 'LASETE', category: 'Camisetas', tone: 'blue', file: 'camiseta_lasete.png', src: '/images/camiseta-lasete.jpg', text: 'Camiseta da Liga Acadêmica de Segurança e Tecnologias Emergentes (UNDB): computador retrô, código Python e muito binário.' },
  { title: 'ODEMI · Melhores momentos', category: 'Posts para redes', tone: 'lime', file: 'stories_odemi.png', src: '/images/odemi-melhores-momentos.jpg', text: 'Stories de melhores momentos do Observatório de Dinâmicas Econômicas e Mercado Internacional, sobre o boletim nº 2.' },
  { title: 'LASTRO', category: 'Marcas e Branding', tone: 'blue', file: 'logo_lastro.svg', src: '/images/lastro-logo.jpg', text: 'Logotipo da Liga Acadêmica de Astropolítica, com estrela, órbita e tipografia espacial.' },
  { title: 'Direito UFMA', category: 'Camisetas', tone: 'yellow', file: 'direito_ufma.png', src: '/images/direito-ufma.jpg', text: 'Arte em colagem para o curso de Direito da UFMA: tipografia repetida e a Justiça em gravura.' },
  { title: 'Banner interativo Servemplac', category: 'Web', tone: 'pink', file: 'servemplac.html', src: '/images/servemplac-banner.jpg', text: 'Banner interativo para o site da Servemplac Digital, levando o usuário direto ao serviço que procura.' },
  { title: 'The UPAONU Times', category: 'Editorial', tone: 'blue', file: 'upaonu_times.pdf', src: '/images/ellen-jornais.jpg', text: 'Criação e diagramação do jornal impresso The UPAONU Times, da capa às páginas internas, pronto pra rodar na gráfica.' },
  { title: 'Teu perfil top', category: 'Posts para redes', tone: 'yellow', file: 'post_final.png', src: '/images/post-perfil-top.jpg', text: 'Post autoral para o @ellenmonroepng: chamada direta, cor forte e humor.' },
]

const categories = ['Todos', 'Posts para redes', 'Marcas e Branding', 'Camisetas', 'Vídeos', 'Web', 'Editorial']
const skills = ['Social Media', 'Tráfego Pago', 'Branding', 'Edição de Vídeo', 'Gravação Audiovisual', 'Criação de Posts', 'Design de Camisetas', 'Direção Criativa', 'Inovação', 'Frontend', 'Telemetria e Sistemas']

function WindowBar({ title }: { title: string }) {
  return <div className="window-bar"><span className="window-dots"><i /><i /><i /></span><span>{title}</span><span className="window-mini">— □ ×</span></div>
}

function SectionTitle({ eyebrow, title, light = false }: { eyebrow: string; title: ReactNode; light?: boolean }) {
  return <div className={`section-title ${light ? 'section-title-light' : ''}`}><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div>
}

export default function Page() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [activeExperience, setActiveExperience] = useState(0)
  const [category, setCategory] = useState('Todos')
  const [selectedProject, setSelectedProject] = useState<Project | null>(null)
  const filtered = useMemo(() => category === 'Todos' ? projects : projects.filter((project) => project.category === category), [category])

  return (
    <main>
      <header className="site-header"><div className="nav-window"><a className="brand" href="#inicio">EM<span>✦</span></a><nav className={menuOpen ? 'nav-links is-open' : 'nav-links'}>{['Início', 'Sobre', 'Experiências', 'Trabalhos', 'Aptidões', 'Contato'].map((item) => <a key={item} href={`#${item.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace('ê', 'e')}`} onClick={() => setMenuOpen(false)}>{item}</a>)}<a className="nav-cta" href="#contato">Fale comigo <ArrowUpRight size={15} /></a></nav><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Abrir menu">{menuOpen ? <X /> : <Menu />}</button></div></header>

      <section id="inicio" className="hero section-pad"><div className="hero-sky"><span className="pixel-cloud cloud-one">▰▰</span><span className="pixel-cloud cloud-two">▰▰▰</span><span className="sun">✹</span></div><div className="hero-copy"><div className="status-pill"><Circle size={9} fill="currentColor" /> Aberta a novas oportunidades</div><h1><span className="h1-ellen">Ellen</span><em>Monroe</em></h1><p className="hero-lede">Eu crio design que <strong>comunica, emociona</strong> e inova.</p><a className="button button-dark" href="#trabalhos">Ver meus trabalhos <ArrowUpRight size={17} /></a></div><div className="hero-photo photo-left"><span>foto_01.jpg</span><img className="photo-img portrait" src="/images/ellen-jornais.jpg" alt="Ellen segurando exemplares do jornal The UPAONU Times" /><small>Designer</small></div><div className="hero-photo photo-right"><span>recorte_02.png</span><img className="photo-img landscape" src="/images/ellen-recorte.jpg" alt="Retrato recortado da Ellen com fundo pêssego" /><small>Dev Frontend</small></div><div className="sticker sticker-yellow">Audiovisual</div><div className="sticker sticker-pink">+ criatividade</div><div className="hero-bottom"><span>SCROLL PARA CONHECER</span><div className="rail-line"><span className="rail-train"><TrainFront size={22} /></span></div><span>01 / 10</span></div></section>

      <section id="sobre" className="about section-pad cream-bg"><div className="about-grid"><div className="about-visual"><div className="hill-scene"><div className="hill hill-back" /><div className="hill hill-front" /></div><div className="tape tape-a" /><div className="about-card"><img className="photo-img big-portrait" src="/images/ellen-retrato.jpg" alt="Retrato da Ellen, de cabelo vermelho e óculos" /></div></div><div className="about-text"><SectionTitle eyebrow="01 / sobre mim" title={<>Oi, eu sou a<br /><span>Ellen!</span> 👋</>} /><p>Sou de São Luís e sou apaixonada por comunicação, criatividade e inovação. Já passei por social media, tráfego pago, branding, design de camisetas e produção audiovisual, e hoje uno tudo isso ao código como desenvolvedora frontend.</p><p>Fundei o <strong>Estúdio Cerise</strong>, onde crio marcas, posts e peças do zero. Gravo, edito e finalizo vídeos no DaVinci Resolve e no CapCut, desenho no Photoshop e no Illustrator, e no dia a dia tenho o Canva como ferramenta principal.</p><p>Estagiei na <strong>Vale, na Estrada de Ferro Carajás</strong>, onde desenvolvi aplicações de telemetria e de manutenção de locomotivas. Aprendi como um trem funciona por dentro e por que a ferrovia é tão importante para o Maranhão.</p><p className="highlight-line">Boa comunicação é aquela que as pessoas sentem, não só veem. <Sparkles size={18} /></p></div></div></section>

      <section id="experiencias" className="experience section-pad wine-bg"><div className="experience-grid"><div><SectionTitle light eyebrow="02 / por onde passei" title={<>Experiências<br /><span>que deixam marca.</span></>} /><p className="section-intro light-copy">Um pouco do caminho que me trouxe até aqui, entre ideias, telas e trilhos.</p><div className="ticket-mini"><TrainFront size={19} /><span>SLZ → próximos destinos</span></div></div><div className="folder-stack">{experiences.map((item, index) => <button key={item.title} className={`folder-tab ${item.color} ${activeExperience === index ? 'active' : ''}`} onClick={() => setActiveExperience(activeExperience === index ? -1 : index)}><div className="folder-label"><span className="folder-index">0{index + 1}</span><span><strong>{item.title}</strong><small>{item.role}</small></span>{item.current && <b className="current-tag">Atual</b>}{item.train && <b className="train-tag">✦ trilhos</b>}<ChevronDown className="chevron" size={20} /></div>{activeExperience === index && <div className="folder-detail"><p>{item.text}</p>{item.photos && <div className="exp-photos">{item.photos.map((photo, i) => <figure key={photo.src} className={`exp-photo exp-photo-${i}`}><img src={photo.src} alt={photo.caption} loading="lazy" /><figcaption>{photo.caption}</figcaption></figure>)}</div>}{item.train && <span className="rail-stamp">Vale · EFC / 2025–2026</span>}</div>}</button>)}</div></div></section>

      <section className="code-rails section-pad"><div className="telemetry-window"><WindowBar title="do_código_aos_trilhos.exe" /><div className="telemetry-content"><div><span className="eyebrow">03 / uma conexão diferente</span><h2>Do código<br /><span>aos trilhos.</span> <TrainFront size={34} /></h2><p>Antes de desenhar pra tela, eu construí sistemas pra locomotivas.</p></div><div className="app-cards">{['Telemetria', 'Manutenção de Locomotivas', 'Outras aplicações'].map((name, i) => <div className="app-card" key={name}><div className={`app-icon app-${i}`}>{i === 0 ? '◉' : i === 1 ? '⚙' : '✦'}</div><strong>{name}</strong><small>{i === 0 ? 'dados em movimento' : i === 1 ? 'cuidado nos detalhes' : 'em construção...'}</small><span className="online"><i /> online</span></div>)}</div><div className="meter"><span>CPU</span><div><i /></div><b>87%</b></div></div></div></section>

      <section id="trabalhos" className="works section-pad cream-bg"><SectionTitle eyebrow="04 / portfólio" title={<>Meus trabalhos<br /><span>falam por mim.</span></>} /><div className="category-tabs">{categories.map((item) => <button className={category === item ? 'active' : ''} onClick={() => setCategory(item)} key={item}>{item}</button>)}</div><div className="project-grid">{filtered.map((project, index) => <button className={`project-card ${project.tone} project-${index}`} key={project.title} onClick={() => setSelectedProject(project)}><div className="project-window"><WindowBar title={project.file} /><div className="project-art">{project.video ? <video src={project.video} poster={project.src} autoPlay muted loop playsInline preload="metadata" /> : <img src={project.src} alt={project.title} loading="lazy" />}<small>{project.video ? '▶ reels' : 'clique para abrir ↗'}</small></div></div><div className="project-caption"><strong>{project.title}</strong><span>{project.category}</span></div></button>)}</div></section>

      <div className="marquee"><div>ELLEN ✦ CRIATIVIDADE ✦ INOVAÇÃO ✦ ELLEN ✦ SÃO LUÍS ✦ ELLEN ✦ CRIATIVIDADE ✦ INOVAÇÃO ✦</div></div>

      <section id="aptidoes" className="skills section-pad"><div className="skills-head"><SectionTitle eyebrow="05 / caixa de ferramentas" title={<>Aptidões que<br /><span>fazem acontecer.</span></>} /><span className="hand-note">arrasta a criatividade ↗</span></div><div className="skills-layout"><div className="tool-grid">{['Canva', 'Photoshop', 'Illustrator', 'DaVinci Resolve', 'CapCut', 'React', 'Next.js', 'Tailwind'].map((tool, i) => <div className={`tool-icon tool-${i}`} key={tool}><span>{['✦', 'Ps', 'Ai', '▶', '✂', '⚛', 'N', '≋'][i]}</span><strong>{tool}</strong>{tool === 'Canva' && <small>uso diário</small>}</div>)}</div><div className="skill-cloud">{skills.map((skill, i) => <span key={skill} className={`skill-pill pill-${i % 5}`}>{skill}</span>)}<div className="progress-card"><div><span>Criatividade</span><b>100%</b></div><div className="xp-progress"><i style={{ width: '100%' }} /></div><div><span>Curiosidade</span><b>95%</b></div><div className="xp-progress"><i style={{ width: '95%' }} /></div></div></div></div></section>

      <section className="why section-pad wine-bg"><div className="ticket"><div className="ticket-side"><span>REFSSA<br />MUSEU</span><TrainFront size={38} /><small>SLZ · 2026</small></div><div className="ticket-main"><span className="eyebrow">06 / por que eu</span><h2>Bilhete pro Reffsa <span>💌</span></h2><p>Eu cresci numa cidade em que a história está nas paredes, e poucos lugares contam isso como o Museu Ferroviário e Portuário. Um prédio de 1929, restaurado, que guarda a memória dos trilhos e do porto do Maranhão e ainda abriga um polo tecnológico. Passado e futuro no mesmo endereço.</p><p>Na Vale, na Estrada de Ferro Carajás, eu não só estagiei: desenvolvi aplicações de telemetria e de manutenção das locomotivas. Conheço o trem por dentro, do código à oficina, e entendo por que a ferrovia é tão importante para o nosso estado.</p><p>Quero contar essa história pro público pelo lado da comunicação e do design. Levar o museu pras telas com posts, vídeos e identidade visual que façam São Luís querer visitar, com calor, cor e curiosidade.</p><span className="hand-note ticket-note">quero embarcar! ↗</span></div></div></section>

      <section id="contato" className="contact section-pad"><div className="contact-heading"><span className="eyebrow">07 / vamos conversar</span><h2>Bora criar<br /><em>juntos?</em></h2><p>Tem uma ideia, um projeto ou uma história boa pra contar? Minha caixa de entrada está aberta.</p></div><div className="msn-window"><WindowBar title="Ellen Monroe · online" /><div className="msn-body"><div className="msn-avatar">EM</div><div><strong>ellen_monroe</strong><p>Oi! Quer criar algo que as pessoas sintam? Me chama. ♡</p></div></div><div className="contact-links"><a href="https://wa.me/5598988442519" target="_blank" rel="noreferrer"><MessageCircle /> WhatsApp <ArrowUpRight /></a><a href="mailto:ellenmonroediniz@gmail.com"><Mail /> E-mail <ArrowUpRight /></a><a href="https://www.linkedin.com/in/ellenmonroediniz" target="_blank" rel="noreferrer"><BriefcaseBusiness /> LinkedIn <ArrowUpRight /></a><a href="#contato"><UserRound /> Instagram <ArrowUpRight /></a></div></div></section>

      <footer><div className="footer-rails"><TrainFront size={21} /></div><span>ELLEN MONROE © 2026</span></footer>
      {selectedProject && <div className="modal-backdrop" role="presentation" onClick={() => setSelectedProject(null)}><div className={`project-modal ${selectedProject.tone}`} role="dialog" aria-modal="true" aria-label={selectedProject.title} onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={() => setSelectedProject(null)} aria-label="Fechar"><X /></button><div className="modal-art">{selectedProject.video ? <video src={selectedProject.video} poster={selectedProject.src} controls autoPlay playsInline /> : <img src={selectedProject.src} alt={selectedProject.title} />}</div><span className="eyebrow">{selectedProject.category}</span><h2>{selectedProject.title}</h2><p>{selectedProject.text}</p><button className="button button-dark" onClick={() => setSelectedProject(null)}>Fechar janela</button></div></div>}
    </main>
  )
}
